name: Run tests and release

on: push

jobs:
  test:
    uses: csm10495/actions/.github/workflows/pytest.yml@master
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "3.11"]'
      operating-systems: '["windows-latest"]'

  version-bump:
    needs: test
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    uses: csm10495/actions/.github/workflows/version-bump.yml@master

  pdoc3:
    needs: version-bump
    if: github.event_name != 'pull_request'
    uses: csm10495/actions/.github/workflows/pdoc3.yml@master
    with:
      python-version: '3.11'
      operating-system: 'windows-latest'

  pypi-upload:
    needs: pdoc3
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    uses: csm10495/actions/.github/workflows/pypi-upload.yml@master
    with:
      python-version: '3.11'
    secrets: inherit

  github-release:
    needs: pdoc3
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    uses: csm10495/actions/.github/workflows/github-release.yml@master
